### ISSUE TITLE
Excldue .DS_Store files on sync

### ISSUE THREAD

**Issue by kuyazee** [Leo0618/flutter-img-sync#10]
.DS_Store files are being added in the sync, please exclude this file when syncing.

```
  /// ![](http://127.0.0.1:9527/assets/.DS_Store)
  static final String assets = 'assets/.DS_Store';
```

**Comment by Leo0618** [comment]
AndroidStudio版本插件已经修复。

升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件
