### ISSUE TITLE
oh crash !!!

### ISSUE THREAD

**Issue by zhangteng709** [Leo0618/flutter-img-sync#13]
lib/r.dart:21:41: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
    Try adding the name of the type of the variable or the keyword 'var'.
      static final String imgsNavBack16x16@2x = 'imgs/navBack_16x16_@2x.png';

**Comment by Leo0618** [comment]
不支持类似@这样的特殊符号，建议仅使用一倍图生成r索引，多倍图@前面的字符串是一样的。
另：升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件
