### ISSUE TITLE
没有生成相关图片资源代码

### ISSUE THREAD

**Issue by jimdaxu** [Leo0618/flutter-img-sync#14]
我按步骤，但是生成的R文件没有对应的资源图片的内容。只有如下内容：
class R {
}

![image](https://user-images.githubusercontent.com/14083020/103717023-65e9ad80-4fff-11eb-9492-354d7fe4f2de.png)

**Comment by foreverGoUp** [comment]
我也是，而且yaml文件里也没有生成图片路径。
我yaml里面配置了而且对于目录下有图片：
# assets-generator-begin
# assets/image/home/*
# assets/image/basic/*
# assets/image/user/*
# assets-generator-end
工具执行后又变为：
# assets-generator-begin
# assets-generator-end

我的环境是AS3.6.3。作者大佬看一下什么原因，感谢~ @Leo0618

**Comment by foreverGoUp** [comment]
解决了....原来编辑完yaml文件要手动ctrl+s保存后，再操作工具生成才可以，建议作者在说明文档中加上这个。 @Leo0618

**Comment by good-good-study** [comment]
我的也是没有自动生成呢，只有一个空的R文件

**Comment by Leo0618** [comment]
升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件
