### ISSUE TITLE
最新插件不支持 Android Studio Bumblebee | 2021.1.1 Patch 3

### ISSUE THREAD

**Issue by Dean-Spotec** [Leo0618/flutter-img-sync#17]
当前版本兼容 203—203.* 麻烦更新下

**Comment by xiaojieonly** [comment]
我也用不了

**Comment by JadeXH** [comment]
Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-17.0.6b829.9-10027231 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.8.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    Dart (223.8950)
    com.jiajun.flutter_add_image (1.7)
    com.nasller.CodeGlancePro (1.6.0)
    com.herbert.george.flutter-snippets (2.0.0-stable-1)
    io.flutter (75.1.2)
    com.ruiyu.ruiyu (5.1.0)

确实是，as里只能看到1.0.2的版本
