### ISSUE TITLE
Android Studio 可以但是 .DS_Store 也会被包含进来, 如果有两个目录都有图片好像不行

### ISSUE THREAD

**Issue by phpmaple** [Leo0618/flutter-img-sync#2]

**Comment by Leo0618** [comment]
如果两个目录都有图片，在通配符里面添加一行，指定图片存放的目录，像这样
`
assets:
# assets-generator-begin
# assets/img/*
# assets/images/*
# assets-generator-end

`

**Comment by dream4java** [comment]
多级目录不生效

**Comment by Leo0618** [comment]
> 多级目录不生效

*通配符是和图片文件同级的，如果多级目录，目前需要配置填写加上，没有做递归遍历目录
比如，img目录下有个app目录，app下面存放的图片，那你需要要这样定义：
assets:
# assets-generator-begin
# assets/img/app/*
# assets-generator-end

**Comment by Leo0618** [comment]
.DS_Store会被包含的问题在1.0.2版本中已解决
