### ISSUE TITLE
2.0x和3.0x文件夹下的图片没有导入

### ISSUE THREAD

**Issue by lvyandev** [Leo0618/flutter-img-sync#3]
RT

**Comment by Leo0618** [comment]
在pubspec.yaml的assets配置下面这样写，就可以配置多个目录下的图片
assets:
# assets-generator-begin
# assets/img/*
# assets/img/2.0x/*
# assets/img/3.0x/*
# assets-generator-end

**Comment by rekcah1986** [comment]
这样配置的话，生成的路径也是带3.0x的吧？

**Comment by xujiaji** [comment]
可否把这个去掉呢😂
![image](https://user-images.githubusercontent.com/16447251/69617413-266a3700-1073-11ea-953a-ea3ade949533.png)
![image](https://user-images.githubusercontent.com/16447251/69617599-65988800-1073-11ea-828d-e4389258956e.png)
