### ISSUE TITLE
预览端口是什么？

### ISSUE THREAD

**Issue by Zheng-Shuo** [Leo0618/flutter-img-sync#5]
作者您好，请问这个预览端口是什么？我应该如何填写？不是太懂，希望指点一二，谢谢。

**Comment by Leo0618** [comment]
请使用新版本，预览功能已取消。

升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件

**Comment by Zheng-Shuo** [comment]
好家伙，这两年你去隔离了嘛。。。
