### ISSUE TITLE
可否加个根据文件名排序呢？

### ISSUE THREAD

**Issue by xujiaji** [Leo0618/flutter-img-sync#7]
由于生成后的名字比较乱，多个人开发的时候都需要手动合并代码呢

**Comment by Leo0618** [comment]
目前没有做排序处理，是按照扫描到文件夹中文件的顺序

**Comment by Leo0618** [comment]
已修复。

升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件
