### ISSUE TITLE
能否按文件夹生成多个文件

### ISSUE THREAD

**Issue by dinoandcat** [Leo0618/flutter-img-sync#8]
图片文件较多时或多人开发时一个R文件放所有信息有些不方便;
能否按文件夹生成多个dart文件;
比如
```
# assets-generator-begin
# assets/images/a/*
# assets/images/b/*
# assets-generator-end
```
生成R_a.dart 和 R_b.dart两个文件

**Comment by Leo0618** [comment]
暂时不支持，以后也不支持，生成一个文件的目的就是统一集中归纳所有的图片，新版本AS插件中对图片多目录情况做了排序、目录分段处理。
升级到1.0.0版本或者下载flutter-img-sync-1.1.0.zip本地安装更新插件
